---
name: Expo Preview Branches
author: Theodo-UK
description: |
  Actions workflow that generates a preview deployment on opening/updating a PR, with auto clean
  up and push to `main` on merge.
branding:
  icon: git-branch
  color: green
runs:
  using: "composite"
inputs:
  token:
    description: >
      GitHub token for GitHub API requests. This should be set automatically, but can be overridden.
    default: ${{ github.token }}
    required: true
