name: Install
description: installs yarn dependencies with caching
inputs:
  EXPO_TOKEN:
    description: Used for eas and expo commands
    required: true

runs:
  using: composite
  steps:
      - name: Check for EXPO_TOKEN
        shell: bash
        run: |
          if [ -z "${{ inputs.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ inputs.EXPO_TOKEN }}

      - name: Find yarn cache
        shell: bash
        id: yarn-cache-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        shell: bash
        run: yarn install --immutable
